### ISSUE TITLE
Window of CCD not working

### ISSUE THREAD

**Issue by tribeiro** [astroufsc/chimera-sbig#3]
subframe not working on this driver.

**Comment by wschoenell** [comment]
@tribeiro Is the binning working or only the Window is not working?

**Comment by tribeiro** [comment]
binning works fine...

**Comment by wschoenell** [comment]
Okay,

The subframing seems to be implemented (although not tested) on the low-level part of the driver:

https://github.com/astroufsc/chimera-sbig/blob/b8032069ceaba0c4fee771db8ab1541ff0c9c9d4/chimera_sbig/instruments/sbigdrv.py#L340-L368

but, when this function is called, what is passed is not the subframe, but the full frame size:

https://github.com/astroufsc/chimera-sbig/blob/b8032069ceaba0c4fee771db8ab1541ff0c9c9d4/chimera_sbig/instruments/sbig.py#L268

**Comment by ankanaan** [comment]
do you know whether this is a problem with chimera or a problem with the
sbig driver?  In what OS is this happening?

On Thu, Jul 23, 2015 at 5:25 PM, William Schoenell <notifications@github.com

**Comment by wschoenell** [comment]
Actually the error seems not to be on the lines above, but somewhere else...

Look to the message error:

```
C:\Anaconda\Scripts>python chimera-cam --subframe 100:200,100:200
========================================
Taking 1 OBJECT frame[s]
Shutter: OPEN
Interval between frames: 0.000s
Cooling enabled, setpoint: -14.810 oC
Current CCD temperature: -11.452 oC
No binning
Subframe: 100:200,100:200     
========================================
synchronizing dome slit ... OK
========================================
[001/001] [08/03/15 16:58:27]
exposing (1.000s) ... OK (took 3.238 s)
reading out and saving ... Traceback (most recent call last):
  File "chimera-cam", line 585, in expose
    object_name=object_name)
  File "C:\Anaconda\lib\site-packages\chimera\core\proxy.py", line 112, in __cal
l__
    return self.sender(self.method, args, kwargs)
  File "C:\Anaconda\lib\site-packages\Pyro\core.py", line 456, in _invokePYRO
    return self.adapter.remoteInvocation(name, Pyro.constants.RIF_VarargsAndKeyw
ords, vargs, kargs)
  File "C:\Anaconda\lib\site-packages\Pyro\protocol.py", line 497, in remoteInvo
cation
    return self._remoteInvocation(method, flags, *args)
  File "C:\Anaconda\lib\site-packages\Pyro\protocol.py", line 572, in _remoteInv
ocation
    answer.raiseEx()
  File "C:\Anaconda\lib\site-packages\Pyro\errors.py", line 72, in raiseEx
    raise self.excObj
ValueError: could not broadcast input array from shape (3072) into shape (101)
 +--- Remote traceback:
 | Traceback (most recent call last):
 |   File "C:\Anaconda\lib\site-packages\Pyro\protocol.py", line 759, in _handle
Invocation2
 |     res = obj.Pyro_dyncall(req[1],flags,req[3])      # (method,flags,args)
 |   File "C:\Anaconda\lib\site-packages\chimera\core\remoteobject.py", line 96,
 in Pyro_dyncall
 |     return getattr(self, method)(*args, **keywords)
 |   File "C:\Anaconda\lib\site-packages\chimera\core\methodwrapper.py", line 11
2, in __call__
 |     return self.call(self.instance, *args, **kwargs)
 |   File "C:\Anaconda\lib\site-packages\chimera\core\lockwrapper.py", line 66,
in call
 |     ret = self.func(*args, **kwargs)
 |   File "C:\Anaconda\lib\site-packages\chimera\instruments\camera.py", line 62
, in expose
 |     return self._baseExpose(request, **kwargs)
 |   File "C:\Anaconda\lib\site-packages\chimera\instruments\camera.py", line 12
1, in _baseExpose
 |     image = self._readout(imageRequest)
 |   File "C:\Anaconda\lib\site-packages\chimera_sbig/instruments\sbig.py", line
 277, in _readout
 |     self.ccd, mode.mode, (left, width))
 | ValueError: could not broadcast input array from shape (3072) into shape (101
)
 +--- End of remote traceback
Error trying to take exposures. (None)
========================================
Total time: 5.080s
========================================
08/03/15 16:58:32
========================================
```
